# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 03dac1d13174188d2433d82777903c871053a1078e73c5c26ea38b087e679b883ff6eb707c8ffb20a3af76556b2ea882010d3c7fc08bba88e2081109dbefc7eb

test:
  secret_key_base: 8f6af3446e2ca2a8294ab1696dc98d40cdae132b25e14be43007e432cc3df6e62b397565e6fa715fc9d3a05d9ed57e82696a6e9097d2e149845e7945ed5c5135

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
